[project]
name = "helix"
version = "1.0.0"
queries = "./db/"

[local.prod]
build_mode = "release"
mcp = true
bm25 = true
# db_max_size_gb = 100

# [local.prod.vector_config]
# m = 16
# ef_construction = 128
# ef_search = 768
